### ISSUE TITLE
.getDOMNode() is deprecated

### ISSUE THREAD

**Issue by evgeny-matveev** [dpraburaj/meteor-react-spin#1]
.getDOMNode() is deprecated, change to React.findDOMNode(component)

**Comment by licatajustin** [comment]
This was addressed in https://github.com/dpraburaj/meteor-react-spin/pull/2. Should be able to close it now :smile:

**Comment by dpraburaj** [comment]
Closed. Thanks :)

**Comment by cryptoquick** [comment]
Not sure this was deployed. @dpraburaj -- Can you make sure it's on Atmosphere? I'd also recommend adding a link to Atmosphere in this project description. :+1: 

Regardless, this is a great package! Works very well right out of the box. Need to access it from the window object in Webpack builds. :smile_cat:

**Comment by dpraburaj** [comment]
I've bumped the version and published it. I forgot to do so since I mistakenly assumed that the latest commit's code would be pulled automatically by atmosphere.

Glad you find the package useful :)
