### ISSUE TITLE
Infinite spin at the 0 length state.

### ISSUE THREAD

**Issue by TylerShin** [dpraburaj/meteor-react-spin#5]
If there is nothing to subscript (length = 0, but will exists), spinner is endlessly working and I can't render anything.

It occurs when I use spinner with Mixnins & subscriptions: []

If you don't mind, could you fix this please?

**Comment by dpraburaj** [comment]
Sorry for the late reply, I was caught up at work. I'll fix this issue this weekend.

**Comment by TylerShin** [comment]
Thanks for reply!
then, I'll look forward to your work. :+1: 

Thank you again!

**Comment by TylerShin** [comment]
For helping you, I added information what I found out.

if there is no data to subscribe (publish 0 count mongo cursor(data) ),
subscribe function return object that has ready() function.

but the ready() return false.

ex) 
there is no post at DB.
postSubs = Meteor.subscribe('posts')

postSubs ==> object Exists.
postSubs.ready() ===> false

that's it. 

I wish that you will fix this problem.

**Comment by dpraburaj** [comment]
Hi, sorry again for the late reply. 

I have fixed the issue in the latest version, can you try upgrading your package and see if the issue persists?

**Comment by TylerShin** [comment]
Thank you! I'll try!
